postgres:
  image: postgres
  environment:
    - "POSTGRES_USER=panoptes"
    - "POSTGRES_PASSWORD=panoptes"
    - "POSTGRES_POOL=64"
  ports:
    - "6000:5432"

zookeeper:
  image: zooniverse/zookeeper
  command: /usr/share/zookeeper/bin/zkServer.sh start-foreground -c localhost:2888:3888 -i 1

cellect:
  build: .
  dockerfile: Dockerfile.dev
  volumes:
    - ./:/cellect_panoptes
  ports:
    - "4000:80"
  environment:
    - "RACK_ENV=development"
    - "DEBUG_CELLECT_START=true"
    - "PUMA_MAX_THREADS=16"
    # - "PRELOAD_WORKFLOWS=1"
  links:
    - postgres:pg
    - zookeeper:zk
